/**
 * Rendering images auto-trimmed so the product fills its frame (the Drexel
 * renderings carry large empty margins, so the subject was showing at a
 * fraction of the box). Generated by afs-overnight/trace/trim_images.py:
 * background colour from the border, subject bounding box, 7% margin.
 *
 * Deliberately NOT trimmed: the brick-wall context shots (Econo Gravel Stop,
 * Gravel Stop), the fascia/rake products and the gutter, which already fill
 * their frame; the DMC seam close-ups, which are full-bleed.
 */
export const TRIMMED_PRODUCT_IMAGES: Readonly<Record<string, string>> = {
  'econo-coping-lt': '/images/products-trim/econo-coping-lt.webp',
  'econo-coping': '/images/products-trim/econo-coping.webp',
  'snap-coping-max': '/images/products-trim/snap-coping-max.webp',
  'rib-mechanically-seamed-flat-panel': '/images/products-trim/flat-panel.webp',
  'rib-mechanically-seamed-striations': '/images/products-trim/striations.webp',
  'rib-snap-lock-striations': '/images/products-trim/sl-ribs-striations.webp',
  'rib-snap-lock-flat': '/images/products-trim/snap-lock-flat.webp',
  'trim-drip-edge': '/images/products-trim/drip-edge.webp',
  'j-channel': '/images/products-trim/j-channel.webp',
  'perforated-z-closure': '/images/products-trim/perforated-z-closure-web.webp',
  'ridge-cap': '/images/products-trim/ridge-cap.webp',
  'ridge-trim': '/images/products-trim/ridge-trim.webp',
  't-style-drip-edge': '/images/products-trim/t-style-drip-edge.webp',
  'trims-offset-cleat': '/images/products-trim/trims-offset-cleat-final.webp',
  'trims-reglet': '/images/products-trim/trims-reglet-final-01.webp',
  'trims-zee': '/images/products-trim/trims-zee-final-01.webp',
  'eave-trim-sample-02': '/images/products-trim/eave-trim-sample-02.webp',
  'gable-sample-02': '/images/products-trim/gable-sample-02.webp',
  'peak-sample-02': '/images/products-trim/peak-sample-02.webp',
  'soffit-j-sample-02': '/images/products-trim/soffit-j-sample-02.webp',
  'vented-ridge-sample-02': '/images/products-trim/vented-ridge-sample-02.webp',
};
