/**
 * THE QUOTE EMAIL, AND ITS APPROVE BUTTON.
 *
 * Built on `baseEmailTemplate` (lib/resend/templates/base.ts) so it looks like
 * every other message this site sends. The literal hex here is the same
 * documented exception that file records: an email client renders this HTML in
 * isolation and can resolve neither a Tailwind class nor a CSS custom property
 * (DESIGN_TOKENS.md §10, CLAUDE.md rule #4's CANVAS_COLORS exception).
 *
 * THE PRICES IN HERE ARE ALLOWED. CLAUDE.md's business rule is that a customer
 * sees a dollar amount only on a formal AFS-generated quote or invoice — this
 * IS that quote, generated by AFS from Steve's own price book, sent
 * deliberately. It is not a storefront price and it is not an estimate.
 *
 * THE APPROVE BUTTON IS A LINK, NOT A FORM. It has to survive every mail client
 * there is, so it is an <a> styled as a button, and the URL beside it is
 * printed in full for the clients that strip styling.
 */
import { baseEmailTemplate } from '@/lib/resend/templates/base';
import { formatCents } from '@/lib/pricing/quote-math';
import type { QuoteLine } from '@/lib/pricing/types';

const COLORS = {
  green: '#1E7F45',
  ink: '#111111',
  inkSoft: '#374151',
  rule: '#D8D8D4',
  white: '#FFFFFF',
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * ONE SURCHARGE ROW, SHARED BY THE QUOTE AND THE INVOICE.
 *
 * It exists because the TOTAL has to add up from what is printed above it. The
 * rush surcharge is deliberately not a `QuoteLine` — a fee has no material, no
 * blank width, no strips-per-sheet and no price-book version, and inventing
 * those would put fabricated geometry on a customer's document (see
 * lib/pricing/rush-policy.ts). So it is a row of its own, and it renders ONLY
 * when there is a figure: a `$0.00` line is noise, and a rush nobody has priced
 * must never appear as though it had been priced at nothing.
 */
function surchargeRow(cents: number | null | undefined, label: string | null | undefined): string {
  if (typeof cents !== 'number' || !Number.isFinite(cents) || cents <= 0) return '';
  return `<tr>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};color:${COLORS.ink};">
          ${escapeHtml(label ?? 'Rush fabrication — priority scheduling')}
        </td>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};text-align:right;color:${COLORS.ink};white-space:nowrap;">
          ${formatCents(cents)}
        </td>
      </tr>`;
}

export interface QuoteEmailInput {
  customerName: string | null;
  quoteNumber: string;
  jobName: string | null;
  lines: QuoteLine[];
  /** Lines PLUS `surchargeCents`. What the Approve button commits them to. */
  totalCents: number;
  /** The rush surcharge AFS decided, or null when there is none to show. */
  surchargeCents?: number | null;
  /** SPEC_RUSH_ORDER.md's own wording, supplied by the caller. No rate in it. */
  surchargeLabel?: string | null;
  approveUrl: string;
  expiresAt: Date;
  revision: number;
}

export function quoteEmailHtml(input: QuoteEmailInput): string {
  const rows = input.lines
    .map((line) => {
      const spec = [line.material, line.gauge, `${line.bendCount} bends`, `${line.hemCount} hems`]
        .filter(Boolean)
        .join(' · ');
      return `<tr>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};">
          <div style="color:${COLORS.ink};font-weight:bold;">${escapeHtml(line.description)} × ${line.quantity}</div>
          <div style="color:${COLORS.inkSoft};font-size:12px;">${escapeHtml(spec)}</div>
        </td>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};text-align:right;color:${COLORS.ink};white-space:nowrap;">
          ${formatCents(line.lineTotalCents)}
        </td>
      </tr>`;
    })
    .join('');

  const expiry = input.expiresAt.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  return baseEmailTemplate(`
    <h1 style="font-size:20px;margin:0 0 4px;">${input.revision > 1 ? 'Revised quote' : 'Your quote'} ${escapeHtml(
      input.quoteNumber
    )}</h1>
    ${input.jobName ? `<p style="margin:0 0 16px;color:${COLORS.inkSoft};">${escapeHtml(input.jobName)}</p>` : ''}
    <p style="margin:0 0 16px;">Hi ${escapeHtml(input.customerName ?? 'there')},</p>
    <p style="margin:0 0 16px;">Here is your quote from Architectural Flashing Supply.${
      input.revision > 1 ? ' This replaces the quote we sent before.' : ''
    }</p>

    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 8px;">
      ${rows}
      ${surchargeRow(input.surchargeCents, input.surchargeLabel)}
      <tr>
        <td style="padding:12px 0;font-weight:bold;color:${COLORS.ink};font-size:16px;">Total</td>
        <td style="padding:12px 0;text-align:right;font-weight:bold;color:${COLORS.ink};font-size:16px;">
          ${formatCents(input.totalCents)}
        </td>
      </tr>
    </table>
    <p style="margin:0 0 24px;color:${COLORS.inkSoft};font-size:12px;">
      Freight and tax are quoted separately once we confirm the delivery address.
    </p>

    <p style="margin:0 0 8px;">Happy with it? One click is all we need.</p>
    <table cellpadding="0" cellspacing="0" style="margin:0 0 12px;">
      <tr><td style="background:${COLORS.green};border-radius:4px;">
        <a href="${input.approveUrl}"
           style="display:inline-block;padding:16px 36px;color:${COLORS.white};font-weight:bold;font-size:16px;text-decoration:none;font-family:Arial,Helvetica,sans-serif;">
          Approve this quote
        </a>
      </td></tr>
    </table>
    <p style="margin:0 0 16px;color:${COLORS.inkSoft};font-size:12px;">
      If the button does not work, copy this link into your browser:<br>
      <span style="word-break:break-all;">${escapeHtml(input.approveUrl)}</span>
    </p>
    <p style="margin:0 0 8px;color:${COLORS.inkSoft};font-size:12px;">
      This link works once and expires on ${escapeHtml(expiry)}. Approving it tells us to start
      fabrication and sends you an invoice — it does not take a payment.
    </p>
    <p style="margin:0;color:${COLORS.inkSoft};font-size:12px;">
      Questions, or something not right? Just reply to this email.
    </p>
  `);
}

export interface InvoiceEmailInput {
  /** 'customer' reads as a bill; 'office' reads as a filing copy. */
  audience: 'customer' | 'office';
  customerName: string | null;
  customerCompany: string | null;
  invoiceNumber: string;
  quoteNumber: string | null;
  jobName: string | null;
  lines: QuoteLine[];
  /** COPIED from the quote, never recomputed — lines plus the surcharge. */
  totalCents: number;
  /** Also copied from the quote, so the invoice reads exactly as it did. */
  surchargeCents?: number | null;
  surchargeLabel?: string | null;
  approvedAt: Date;
}

export function invoiceEmailHtml(input: InvoiceEmailInput): string {
  const rows = input.lines
    .map(
      (line) => `<tr>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};color:${COLORS.ink};">
          ${escapeHtml(line.description)} × ${line.quantity}
        </td>
        <td style="padding:8px 0;border-bottom:1px solid ${COLORS.rule};text-align:right;color:${COLORS.ink};white-space:nowrap;">
          ${formatCents(line.lineTotalCents)}
        </td>
      </tr>`
    )
    .join('');

  const who = [input.customerName, input.customerCompany].filter(Boolean).join(' — ') || 'the customer';
  const approved = input.approvedAt.toLocaleString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });

  const intro =
    input.audience === 'office'
      ? `<p style="margin:0 0 16px;">${escapeHtml(who)} approved quote ${escapeHtml(
          input.quoteNumber ?? '—'
        )} on ${escapeHtml(approved)}. The invoice below was created from that quote automatically — nothing was re-typed.</p>`
      : `<p style="margin:0 0 16px;">Hi ${escapeHtml(
          input.customerName ?? 'there'
        )}, thank you for approving your quote. Here is your invoice.</p>`;

  return baseEmailTemplate(`
    <h1 style="font-size:20px;margin:0 0 4px;">Invoice ${escapeHtml(input.invoiceNumber)}</h1>
    ${input.jobName ? `<p style="margin:0 0 16px;color:${COLORS.inkSoft};">${escapeHtml(input.jobName)}</p>` : ''}
    ${intro}
    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 8px;">
      ${rows}
      ${surchargeRow(input.surchargeCents, input.surchargeLabel)}
      <tr>
        <td style="padding:12px 0;font-weight:bold;color:${COLORS.ink};font-size:16px;">Total</td>
        <td style="padding:12px 0;text-align:right;font-weight:bold;color:${COLORS.ink};font-size:16px;">
          ${formatCents(input.totalCents)}
        </td>
      </tr>
    </table>
    <p style="margin:0;color:${COLORS.inkSoft};font-size:12px;">
      Freight and tax are billed separately once the delivery address is confirmed.
    </p>
  `);
}
