import type { SupabaseClient } from '@supabase/supabase-js';
import { sendEmail } from '@/lib/resend/send';
import { baseEmailTemplate, ctaButton } from '@/lib/resend/templates/base';
import { getSiteUrl } from '@/lib/site-url';

const APP_URL = getSiteUrl();

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
});

const DUE_SOON_DAYS = 7;

export interface BidAlertProject {
  id: string;
  title: string;
  sourceName: string;
  locationCity: string | null;
  locationState: string | null;
  bidDueDate: string | null; // ISO string
  estimatedValue: number | null;
  keywordsMatched: string[];
  sourceUrl: string | null;
}

export interface SendBidAlertResult {
  sent: boolean;
  recipients: string[];
  errors: string[];
}

/**
 * BID_MONITOR_ALERT_EMAIL (.env.example) overrides the primary recipient so
 * this stays configurable without a code change; steve@ is a second,
 * always-on recipient per the original request. Deduped in case the env var
 * is ever set to the same address.
 */
function getAlertRecipients(): string[] {
  const primary = process.env.BID_MONITOR_ALERT_EMAIL || 'tricia@architecturalflashingsupply.com';
  return Array.from(new Set([primary, 'steve@architecturalflashingsupply.com']));
}

function isDueSoon(bidDueDate: string | null): boolean {
  if (!bidDueDate) return false;
  const due = new Date(bidDueDate).getTime();
  if (Number.isNaN(due)) return false;
  const daysUntilDue = (due - Date.now()) / (1000 * 60 * 60 * 24);
  return daysUntilDue >= 0 && daysUntilDue <= DUE_SOON_DAYS;
}

function formatDueDate(bidDueDate: string | null): string {
  if (!bidDueDate) return 'Not specified';
  const due = new Date(bidDueDate);
  if (Number.isNaN(due.getTime())) return 'Not specified';
  return due.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function formatLocation(city: string | null, state: string | null): string {
  if (city && state) return `${city}, ${state}`;
  return city || state || 'Location not specified';
}

function projectCardHtml(project: BidAlertProject): string {
  const dueDateHtml = isDueSoon(project.bidDueDate)
    ? `<span style="color:#C0001A;font-weight:700;">${formatDueDate(project.bidDueDate)} (due soon)</span>`
    : formatDueDate(project.bidDueDate);
  const valueHtml = project.estimatedValue ? currency.format(project.estimatedValue) : 'Not specified';
  const keywordsHtml = project.keywordsMatched.length > 0 ? project.keywordsMatched.join(', ') : 'None';
  const viewOpportunityButton = project.sourceUrl ? ctaButton(project.sourceUrl, 'View Opportunity →') : '';
  const openBidMonitorButton = ctaButton(`${APP_URL}/admin/bid-monitor`, 'Open Bid Monitor →');

  return `
    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;border:1px solid #E5E5E5;border-radius:4px;">
      <tr><td style="padding:20px;">
        <h2 style="font-size:16px;margin:0 0 12px;color:#111111;">${project.title}</h2>
        <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;color:#374151;">
          <tr><td style="padding:3px 0;width:150px;font-weight:700;">Source:</td><td style="padding:3px 0;">${project.sourceName}</td></tr>
          <tr><td style="padding:3px 0;font-weight:700;">Location:</td><td style="padding:3px 0;">${formatLocation(project.locationCity, project.locationState)}</td></tr>
          <tr><td style="padding:3px 0;font-weight:700;">Bid Due Date:</td><td style="padding:3px 0;">${dueDateHtml}</td></tr>
          <tr><td style="padding:3px 0;font-weight:700;">Estimated Value:</td><td style="padding:3px 0;">${valueHtml}</td></tr>
          <tr><td style="padding:3px 0;font-weight:700;">Keywords Matched:</td><td style="padding:3px 0;">${keywordsHtml}</td></tr>
        </table>
        <div>${viewOpportunityButton}${openBidMonitorButton}</div>
      </td></tr>
    </table>`;
}

export function buildBidAlertEmailHtml(projects: BidAlertProject[]): string {
  const cards = projects.map(projectCardHtml).join('');
  return baseEmailTemplate(`
    <h1 style="font-size:20px;margin:0 0 20px;">AFS Bid Monitor — New Opportunities</h1>
    ${cards}
    <p style="margin:24px 0 0;font-size:12px;color:#7A8299;">
      This alert was generated by AFS Bid Monitor. Manage alerts at
      <a href="${APP_URL}/admin/bid-monitor" style="color:#C0001A;">/admin/bid-monitor</a>.
    </p>
  `);
}

export function buildBidAlertSubject(projectCount: number): string {
  return `AFS Bid Monitor — ${projectCount} New Opportunit${projectCount === 1 ? 'y' : 'ies'} Found`;
}

/**
 * Sends the new-opportunities alert email to every configured recipient and
 * logs one bid_alerts row per (project, recipient) pair. `supabase` is the
 * caller's own session-scoped client — bid_alerts is admin-only RLS
 * (010_bid_monitor.sql), so this must only be called after the caller has
 * already verified an admin session; both app/api/bid-monitor/alert/route.ts
 * and app/api/bid-monitor/fetch/route.ts do that before calling in here.
 * Never throws — matches ARCHITECTURE.md §9's "notification failure must
 * never block" rule.
 */
export async function sendBidAlertEmails(
  supabase: SupabaseClient,
  projects: BidAlertProject[]
): Promise<SendBidAlertResult> {
  if (projects.length === 0) {
    return { sent: false, recipients: [], errors: ['No new Division 7 opportunities to alert on.'] };
  }

  const recipients = getAlertRecipients();
  const subject = buildBidAlertSubject(projects.length);
  const html = buildBidAlertEmailHtml(projects);

  const errors: string[] = [];
  let anySent = false;

  for (const recipient of recipients) {
    const emailResult = await sendEmail({ to: recipient, subject, html });
    if (emailResult.success) {
      anySent = true;
    } else {
      errors.push(`${recipient}: ${emailResult.error ?? 'unknown error'}`);
    }

    try {
      const { error: logError } = await supabase.from('bid_alerts').insert(
        projects.map((project) => ({
          project_id: project.id,
          alert_type: 'new_match',
          sent_to: recipient,
        }))
      );
      if (logError) {
        errors.push(`Could not log bid_alerts for ${recipient}: ${logError.message}`);
      }
    } catch (logError) {
      errors.push(`Could not log bid_alerts for ${recipient}: ${logError instanceof Error ? logError.message : String(logError)}`);
    }
  }

  return { sent: anySent, recipients, errors };
}
