import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export interface ProfilePdfPoint {
  x: number;
  y: number;
}

export interface ProfilePdfInput {
  name: string;
  jobName: string | null;
  createdAt: string;
  points: ProfilePdfPoint[];
}

const PAGE_WIDTH = 612; // US Letter, points — matches lib/utils/simple-pdf.ts's page geometry
const PAGE_HEIGHT = 792;
const DRAWING_BOX = { x: 56, y: 260, width: 500, height: 400 };

/**
 * "Download PDF" (Profile Passport Profiles tab, Phase 3/afs-pp-001) —
 * unlike lib/utils/simple-pdf.ts's hand-rolled text-only PDFs (used for
 * invoices/bid documents, which have nothing to draw), a saved profile's
 * whole point is its geometry, so this actually renders the polyline —
 * scaled/centered into a fixed drawing box — rather than just listing
 * numbers. Uses pdf-lib (already a project dependency, see
 * app/api/takeoff/route.ts) instead of extending simple-pdf.ts, since
 * simple-pdf.ts has no vector line-drawing primitive at all.
 */
export async function buildProfilePdf(input: ProfilePdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  page.drawText('AFS — Architectural Flashing Supply', {
    x: 56,
    y: PAGE_HEIGHT - 56,
    size: 10,
    font: fontRegular,
    color: rgb(0.6, 0.1, 0.1),
  });
  page.drawText(input.name, {
    x: 56,
    y: PAGE_HEIGHT - 84,
    size: 20,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.12),
  });

  const metaLines = [
    `Job: ${input.jobName ?? '—'}`,
    `Saved: ${new Date(input.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
  ];
  metaLines.forEach((line, i) => {
    page.drawText(line, { x: 56, y: PAGE_HEIGHT - 110 - i * 16, size: 11, font: fontRegular, color: rgb(0.35, 0.35, 0.38) });
  });

  page.drawRectangle({
    x: DRAWING_BOX.x,
    y: DRAWING_BOX.y,
    width: DRAWING_BOX.width,
    height: DRAWING_BOX.height,
    borderColor: rgb(0.85, 0.85, 0.87),
    borderWidth: 1,
  });

  if (input.points.length >= 2) {
    const xs = input.points.map((p) => p.x);
    const ys = input.points.map((p) => p.y);
    const minX = Math.min(...xs);
    const maxX = Math.max(...xs);
    const minY = Math.min(...ys);
    const maxY = Math.max(...ys);
    const spanX = maxX - minX || 1;
    const spanY = maxY - minY || 1;
    const padding = 32;
    const scale = Math.min((DRAWING_BOX.width - padding * 2) / spanX, (DRAWING_BOX.height - padding * 2) / spanY);
    const drawnWidth = spanX * scale;
    const drawnHeight = spanY * scale;
    const offsetX = DRAWING_BOX.x + (DRAWING_BOX.width - drawnWidth) / 2;
    // PDF's y-axis points up; FlashDraft's canvas y-axis points down — flip
    // it here rather than at every call site that hands this function points.
    const offsetY = DRAWING_BOX.y + (DRAWING_BOX.height - drawnHeight) / 2;

    const toPdfPoint = (p: ProfilePdfPoint) => ({
      x: offsetX + (p.x - minX) * scale,
      y: offsetY + (maxY - p.y) * scale,
    });

    for (let i = 0; i < input.points.length - 1; i++) {
      const start = toPdfPoint(input.points[i]);
      const end = toPdfPoint(input.points[i + 1]);
      page.drawLine({ start, end, thickness: 2.5, color: rgb(0.72, 0.02, 0.1) });
    }
  } else {
    page.drawText('No geometry on file.', {
      x: DRAWING_BOX.x + 24,
      y: DRAWING_BOX.y + DRAWING_BOX.height / 2,
      size: 12,
      font: fontRegular,
      color: rgb(0.6, 0.6, 0.62),
    });
  }

  page.drawText('Generated by AFS Profile Passport — for reference only, not a fabrication drawing.', {
    x: 56,
    y: 40,
    size: 8,
    font: fontRegular,
    color: rgb(0.6, 0.6, 0.62),
  });

  return doc.save();
}
