import { generateProfileSVG, slugToProfileType, type ProfileType } from '@/lib/utils/profile-svg';

/**
 * Product slugs whose name does not equal a ProfileType slug but whose
 * cross-section is unambiguous. Anything not listed (scuppers, valley,
 * wall trim, roof panels) deliberately gets NO drawing rather than a
 * look-alike that would misrepresent the product.
 */
const SLUG_TO_PROFILE: Record<string, ProfileType> = {
  'ridge-cap': 'ridge',
  'continuous-cleat': 'cleat',
  'head-flashing': 'door-window-pan',
  'sill-pan-flashing': 'door-window-pan',
  'custom-profile': 'custom-flashing',
  'field-measured-detail': 'custom-flashing',
};

export function resolveProfileType(slug: string, explicit?: ProfileType): ProfileType | null {
  return explicit ?? SLUG_TO_PROFILE[slug] ?? slugToProfileType(slug);
}

interface ProfileThumbProps {
  slug: string;
  profileType?: ProfileType;
  /** Shown when no drawing exists for this item. */
  fallbackLabel: string;
  className?: string;
}

/**
 * Large cross-section drawing for catalog tiles. Dimension labels are hidden
 * on purpose: dimensions belong in FlashDraft, not on a browse tile.
 */
export default function ProfileThumb({ slug, profileType, fallbackLabel, className = '' }: ProfileThumbProps) {
  const type = resolveProfileType(slug, profileType);
  if (!type) {
    return (
      <div
        className={`flex items-center justify-center bg-afs-bg-surface text-afs-chrome-dim font-label text-xs uppercase tracking-widest ${className}`}
      >
        {fallbackLabel}
      </div>
    );
  }
  const markup = generateProfileSVG({ profileType: type, hideDimensions: true });
  return (
    <div
      className={`bg-afs-bg-surface ${className}`}
      // Trusted: generated by our own generateProfileSVG from fixed geometry.
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}
