import { anthropic } from '@/lib/anthropic/client';
import type { MaterialCategory, ReplacementTier, StormEvent } from './types';
import type { MaterialScoreFactors } from './replacement-score';
import type { WindContext } from './wind';

const MATERIAL_LABELS: Record<MaterialCategory, string> = {
  asphalt_shingle: 'asphalt shingle roofing',
  metal_r_panel: 'R-panel metal roofing',
  metal_standing_seam: 'standing seam metal roofing',
  tpo_pvc_membrane: 'TPO/PVC commercial membrane roofing',
  wood_shake: 'wood shake roofing',
};

export interface ExplanationInput {
  address: string;
  material: MaterialCategory;
  score: number;
  tier: ReplacementTier;
  factors: MaterialScoreFactors;
  hailEvents: StormEvent[];
  nonHailEventCount: number;
  wind: WindContext | null;
}

// The score/tier are computed entirely in lib/hailview/replacement-score.ts
// BEFORE this function is ever called, and are passed in here only as
// fixed facts for the model to narrate. This function has no ability to
// change them — it returns prose text, not a score. Do not add any code
// path here that feeds the model's output back into the numeric score.
const HAILVIEW_EXPLANATION_SYSTEM_PROMPT = `You are HailView's report-writing assistant for Architectural Flashing Supply (AFS), a sheet metal fabricator. You are given an ALREADY-COMPUTED, deterministic hail-damage replacement-probability score and tier for one property and one roofing material, plus the storm history and wind data behind it. Your only job is to write a clear, factual narrative explanation of that score for a homeowner, PM, or GC reading a report.

STRICT RULES:
- The numeric score and tier you are given are final and were computed by a separate, deterministic formula before you were called. NEVER state a different score or tier than the one given to you. NEVER imply the score should be higher or lower than what is given. NEVER invent a score if one is not given.
- Do not fabricate hail events, dates, or measurements beyond what is provided in the storm history data.
- Cite specific hail events (date, size, distance) from the data you're given when explaining what drove the score.
- Mention wind speed/direction context if provided, since wind-driven hail causes more directional/severe damage than vertical hail.
- Explain the material-specific factors relevant to this material and score.
- Keep it readable for a non-engineer: 3-5 short paragraphs, no jargon without a plain-language explanation.
- Never mention pricing, cost, or a quote — this is a diagnostic report, not a sales quote. If replacement or repair seems warranted, tell them to request a formal AFS quote, without stating or estimating any dollar figure.
- Do not mention that you are an AI or that this explanation was generated by a model.`;

function formatHailEventsForPrompt(events: StormEvent[]): string {
  if (events.length === 0) return 'No hail events recorded within 1 mile in the last 5 years.';
  return events
    .map((e) => `- ${e.validAt.slice(0, 10)}: ${e.sizeIn}" hail, ${e.distanceMi.toFixed(2)}mi from address${e.city ? `, near ${e.city}` : ''}`)
    .join('\n');
}

export async function generateHailViewExplanation(input: ExplanationInput): Promise<string> {
  const materialLabel = MATERIAL_LABELS[input.material];

  const windLine = input.wind
    ? `On the date of the largest hail event (${input.wind.sampledDate}), the recorded max wind gust was ${input.wind.maxGustMph} mph from the ${input.wind.directionAtMaxGust}.`
    : 'Wind speed/direction data was not available for this report.';

  const userPrompt = `Property: ${input.address}
Material: ${materialLabel}

COMPUTED SCORE (final, do not alter): ${input.score}/100 — ${input.tier} replacement probability

Score factors:
- Largest single hail event contribution: ${input.factors.largestEventContribution.toFixed(1)} points${input.factors.largestEvent ? ` (${input.factors.largestEvent.sizeIn}" hail on ${input.factors.largestEvent.validAt.slice(0, 10)})` : ' (no qualifying hail event found)'}
- Cumulative wear from ${input.factors.cumulativeQualifyingCount} additional qualifying event(s): ${input.factors.cumulativeContribution.toFixed(1)} points
- Frequency escalation bonus (${input.factors.qualifyingEventCount} total qualifying events): ${input.factors.frequencyBonus} points
${input.factors.multiplierLabel ? `- ${input.factors.multiplierLabel}: ${input.factors.multiplierApplied.toFixed(2)}x` : ''}

Hail history (within 1 mile, last 5 years):
${formatHailEventsForPrompt(input.hailEvents)}

Other (non-hail) storm reports in the area over the same period: ${input.nonHailEventCount}

Wind context: ${windLine}

Write the narrative explanation now.`;

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1200,
    system: HAILVIEW_EXPLANATION_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const textBlock = response.content.find((b) => b.type === 'text');
  return textBlock && textBlock.type === 'text' ? textBlock.text : '';
}
